### ISSUE TITLE
TypeError: Plot.registerNotificationFilter is not a function

### ISSUE THREAD

**Issue by nick-silverchip** [Plotprojects/plotprojects-react-native-module#5] opened 2022-02-22 14:45 UTC
Hi, I'm using the plot-projects-react-native-module package in an app and the functionality was working until a recent update.

If I use version 1.0.7 of the package I get an error when I try to call Plot.registerNotificationFilter:

TypeError: Plot.registerNotificationFilter is not a function

Looking at the PlotProjects module (defined above as 'Plot') in a console log, I can see that the method 'registerNotificationFilter' does not exist.

If I roll back the version to 1.0.5 then everything works fine again.

Is there an undocumented change to the API for v1.0.7?

**Comment by yahya-plotprojects** [comment] 2022-02-24 14:34
Hello Nick,

I am not able to reproduce the issue you are facing but it sounds like an issue with cache. The internals of registerNotificationFilter method have changed between 1.0.5 and 1.0.7 but the API has not. It looks like somehow the implementation of 1.0.5 is still cached on react native server while it picked up the implementation of 1.0.7 on the native apps part.
I suggest to try to clean all caches and rerun again. You can do that by using the `--reset-cache` flag on react native cmd tools and clean the build on both Android and iOS apps.

I should also mention that version 1.0.8 is already out and it has further improvements on handlers in general.

If you are still facing the same issue after resetting the cache, please let me know. Otherwise, I will close this issue

**Comment by yahya-plotprojects** [comment] 2022-04-29 12:57
This issue is fixed in 1.0.9

**Closed as completed** 2022-04-29 12:57 UTC
